// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Append(arg1, arg2) {
  return window['go']['app']['App']['Append'](arg1, arg2);
}

export function BackupFolder(arg1) {
  return window['go']['app']['App']['BackupFolder'](arg1);
}

export function Insert(arg1, arg2) {
  return window['go']['app']['App']['Insert'](arg1, arg2);
}

export function ListPlayers() {
  return window['go']['app']['App']['ListPlayers']();
}

export function LoadHistory(arg1) {
  return window['go']['app']['App']['LoadHistory'](arg1);
}

export function Rollback(arg1) {
  return window['go']['app']['App']['Rollback'](arg1);
}
