// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {player} from '../models';

export function ListPlayers():Promise<Array<player.Player>>;
